### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/cufp-2015#1]
- [x] add ports to `Ip` (renaming `Ip` to `Host`?)
- [x] factor api out into it's own project.
- [x] add template server project
- [x] add an easy way to setup a development environment
- [x] write README
